<a href="https://www.kaggle.com/code/mbu9ua/da-lab-4?scriptVersionId=233904301" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# importing necessary library
import pandas as pd
# load the dataset
df = pd.read_csv(r'/kaggle/input/udemy-courses-dataset/UdemyCoursesDataset.csv')

In [2]:
# Display the first 6 rows
df.head(6)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
5,1122832,#6 Piano Hand Coordination: Play Open 10 Balla...,True,65,2015,3,21,Intermediate Level,44 mins,2017-03-08T17:53:36Z,Musical Instruments

### **1. What are the list of the subjects for which Udemy is offering courses?**

In [3]:
subjects = df['subject'].unique()
print(subjects)

['Musical Instruments' 'Business Finance' 'Graphic Design'
 'Web Development']

### **2. Which subject has the maximum number of courses?**

In [4]:
max_subject = df['subject'].value_counts().idxmax()
print(max_subject)

Web Development

### **3. What is the number of the courses which are Free of Cost?**

In [5]:
free_courses = df[df['is_paid']== False].shape[0]
print(f"Number of free courses: {free_courses}")

Number of free courses: 310

### **4. Show all the courses which are Paid?**

In [6]:
paid_courses = df[df['is_paid']== True].shape[0]
print(f"Number of paid courses: {paid_courses}")

Number of paid courses: 3372

### **5. Which are Top Selling Courses?**

In [7]:
top_selling = df.sort_values(by='num_subscribers', ascending=False)
top_selling[['course_title', 'num_subscribers']].head()

                                           course_title  num_subscribers
2230               Learn HTML5 Programming From Scratch           268923
776                      Coding for Entrepreneurs Basic           161029
3385                         The Web Developer Bootcamp           121584
640   Build Your First Website in 1 Week with HTML5 ...           120291
3316              The Complete Web Developer Course 2.0           114512

### **6. How many number of courses are there in the Intermediate Level?**

In [8]:
intermediate_count = df[df['level'] == 'Intermediate Level'].shape[0]
print(f"Number of Intermediate Level Courses: {intermediate_count}")

Number of Intermediate Level Courses: 421

### **7. Show all courses of Graphic Design where the price is below 100?**

In [9]:
graphic_design_courses = df[(df['subject'] == 'Graphic Design') & (df['price'] <= '100')]
graphic_design_courses

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
47,1269190,7 Secrets To Designing In Black and White,True,100,1000,1,12,All Levels,1.5 hours,2017-06-27T19:55:18Z,Graphic Design
169,983444,Adobe Illustrator Vectors For Hand Letterers,True,100,23,2,9,Beginner Level,37 mins,2016-10-21T18:50:38Z,Graphic Design
184,638040,Adobe Photoshop Essentials: Master Adobe Photo...,True,100,1373,5,63,Beginner Level,2.5 hours,2015-11-18T17:47:26Z,Graphic Design
520,978462,Blender Modelling Series - Volume Two,True,100,1526,3,24,Beginner Level,2 hours,2016-10-12T20:22:14Z,Graphic Design
699,757900,Canva : Book Cover Design,True,100,3377,20,15,Beginner Level,2 hours,2016-02-26T01:08:20Z,Graphic Design
1029,1160004,Design a logo for FREE in Inkscape,True,100,1148,26,42,All Levels,2 hours,2017-05-01T18:32:43Z,Graphic Design
1071,1161864,Diseño impreso - Preimpresión para offset en I...,True,100,33,9,29,All Levels,1.5 hours,2017-05-31T18:37:31Z,Graphic Design
1444,490392,Getting Started with Illustrator CC,True,100,92,10,57,Beginner Level,5.5 hours,2015-05-01T21:29:51Z,Graphic Design
1568,727510,How To Become An Etsy Wholesale Seller,True,100,1013,0,25,Beginner Level,2.5 hours,2016-03-29T22:34:30Z,Graphic Design
1616,996868,How to Design a Logo in Adobe Illustrator,True,100,972,44,24,All Levels,1 hour,2016-11-14T15:26:17Z,Graphic Design
1697,654038,How To Sell Your Art Online With ETSY,True,100,1338,38,35,Beginner Level,3 hours,2015-11-11T01:26:13Z,Graphic Design
1773,1012262,Icon & Logo Symbol Design in Adobe Illustrator,True,100,1043,27,30,All Levels,2 hours,2016-11-23T22:57:18Z,Graphic Design
1786,1246168,"Illustrator para criação de peças gráficas, De...",True,100,33,3,41,Beginner Level,1.5 hours,2017-06-13T04:15:20Z,Graphic Design
1797,1266468,Indesign - Para quem quer trabalhar com Design...,True,100,27,7,12,Intermediate Level,2.5 hours,2017-06-27T02:48:29Z,Graphic Design
2137,927186,Learn Blender 3D - The introduction course,True,100,739,12,15,Beginner Level,1.5 hours,2016-08-19T00:52:30Z,Graphic Design
2481,1027080,Logo Portfolio in 1 Hour in Wordpress,True,100,734,9,36,All Levels,1 hour,2016-12-06T22:13:44Z,Graphic Design
2491,771044,"Make Money With Photoshop: Logos, Business Car...",True,100,32,4,21,All Levels,5 hours,2016-08-14T22:05:04Z,Graphic Design
2576,482924,Mastering Retouching and Restoration (15 proje...,True,100,4927,15,22,All Levels,2.5 hours,2015-04-26T12:27:22Z,Graphic Design
2704,950894,photoshop - CURSO DE PHOTOSHOP DO BÁSICO AO AV...,True,100,1110,183,77,All Levels,10 hours,2017-02-06T17:22:18Z,Graphic Design
2706,1243016,Photoshop - Tratamento de pele profissional,True,100,50,5,16,Intermediate Level,1.5 hours,2017-06-06T14:22:28Z,Graphic Design
2713,1147664,Photoshop CC Eğitim Seti (YENİ),True,100,27,5,202,All Levels,16 hours,2017-03-30T22:26:26Z,Graphic Design
3479,575040,Typography From A to Z,True,100,317,15,76,All Levels,6 hours,2015-08-07T22:16:26Z,Graphic Design
3594,908664,Word Swag : Create Stunning Images with the Wo...,True,100,2416,19,14,All Levels,1 hour,2016-08-09T17:56:53Z,Graphic Design

### **8. List out all the courses that are related with `Python`?**

In [10]:
python_courses = df[df['course_title'].str.contains('python', case=False)]
python_courses

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
216,599504,Advanced Scalable Python Web Development Using...,True,120,1299,56,71,Intermediate Level,14 hours,2016-08-11T22:09:24Z,Web Development
777,47963,"Coding for Entrepreneurs: Learn Python, Django...",True,195,23412,799,251,All Levels,45 hours,2013-04-08T00:46:14Z,Web Development
814,631128,Complete Python Web Course: Build 8 Python Web...,True,110,7489,941,173,All Levels,16 hours,2015-11-08T20:57:35Z,Web Development
842,186096,"Core: A Web App Reference Guide for Django, Py...",True,195,2497,98,154,All Levels,26 hours,2014-05-29T00:58:43Z,Web Development
1400,394832,Fun and creative web engineering with Python a...,False,Free,10917,319,25,All Levels,2 hours,2015-06-09T19:51:50Z,Web Development
1932,1038538,Introduction to QGIS Python Programming,True,85,197,26,28,Beginner Level,3.5 hours,2016-12-22T00:11:22Z,Web Development
1969,902888,Investment Portfolio Analysis with Python,True,50,209,13,37,All Levels,7 hours,2016-07-13T21:40:32Z,Business Finance
2294,391546,Learn Python and Django: Payment Processing,True,70,17714,198,23,All Levels,3.5 hours,2015-02-09T15:37:56Z,Web Development
2295,1063722,Learn Python Django - A Hands-On Course,True,50,1339,21,18,Beginner Level,2 hours,2017-01-18T21:53:34Z,Web Development
2341,546848,Learn to code in Python and learn Adobe Photos...,True,50,1132,1,29,All Levels,2 hours,2015-07-08T00:15:12Z,Graphic Design
2906,368340,Professional Python Web Development Using Flask,True,120,3420,489,102,Beginner Level,14.5 hours,2015-03-04T00:10:36Z,Web Development
2908,1035940,Professional RESTful API Design using Python F...,True,120,578,25,36,Intermediate Level,4.5 hours,2017-01-11T21:15:25Z,Web Development
2929,270808,Projects in Django and Python,True,60,1764,53,28,All Levels,6.5 hours,2014-10-21T07:58:07Z,Web Development
2952,1170894,Python Algo Stock Trading: Automate Your Trading!,True,95,1165,21,41,Beginner Level,2.5 hours,2017-05-28T23:41:03Z,Business Finance
2953,1070886,Python Algo Trading: FX Trading with Oanda,True,200,453,42,33,Intermediate Level,3 hours,2017-03-14T00:39:45Z,Business Finance
2954,1196544,Python Algo Trading: Sentiment Trading with News,True,200,294,19,42,All Levels,7 hours,2017-04-28T16:41:44Z,Business Finance
2955,822444,Python and Django Full Stack Web Developer Boo...,True,200,11832,1883,191,All Levels,31.5 hours,2017-02-24T18:40:55Z,Web Development
2956,477702,Python for Beginners: Python Programming Langu...,True,150,6153,125,84,Beginner Level,5 hours,2015-06-14T18:18:57Z,Web Development
2957,1035472,Python for Finance: Investment Fundamentals & ...,True,195,3811,278,103,All Levels,6.5 hours,2017-03-30T22:17:09Z,Business Finance
2958,529828,Python for Trading & Investing,True,95,638,25,36,All Levels,5 hours,2015-06-17T22:23:31Z,Business Finance
2959,70640,Python Programming: Create an Digital Marketpl...,True,195,4198,145,161,All Levels,26 hours,2013-10-20T19:53:28Z,Web Development
2960,523312,Python Web Programming,True,100,1020,46,60,Beginner Level,6 hours,2015-07-01T21:46:36Z,Web Development
2962,1088656,Quantitative Trading Analysis with Python,True,50,256,17,49,All Levels,5.5 hours,2017-01-27T17:11:28Z,Business Finance
3013,970600,REST APIs with Flask and Python,True,110,5151,737,115,Intermediate Level,12.5 hours,2016-11-06T19:00:38Z,Web Development
3154,815482,Stock Technical Analysis with Python,True,50,409,35,46,All Levels,8 hours,2016-04-12T00:40:03Z,Business Finance
3272,938560,The Complete Ethical Hacking Course 2.0: Pytho...,True,195,7827,268,66,All Levels,11 hours,2016-09-26T15:08:29Z,Web Development
3460,76052,Try Django 1.9 | Build a Blog and Learn Python...,True,50,7407,172,147,All Levels,20 hours,2014-03-04T07:12:21Z,Web Development
3573,16646,Web Programming with Python,True,50,35267,217,53,All Levels,4 hours,2012-04-25T00:01:43Z,Web Development
3574,574082,"Web Scraping with Python, Ruby & import. io",True,75,973,50,46,All Levels,4.5 hours,2015-08-09T22:16:41Z,Web Development

### **9. What are courses that published in year 2015 ?**

In [11]:
df['published_timestamp'] = pd.to_datetime(df['published_timestamp'])

courses_2015 = df[df['published_timestamp'].dt.year == 2015]
courses_2015

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
10,591880,1 - Concepts of Statistics For Beginners Step ...,True,200,273,4,15,Beginner Level,31 mins,2015-08-30 22:48:34+00:00,Business Finance
16,302450,10 Numbers Every Business Owner Should Know,True,20,13,1,9,All Levels,1 hour,2015-03-08 19:11:24+00:00,Business Finance
19,384928,101 Blues riffs - learn how the harmonica supe...,True,200,1350,65,55,Intermediate Level,6.5 hours,2015-01-04 21:14:31+00:00,Musical Instruments
23,550842,16 Guitar Chords to Jam With - (Beginner - Int...,True,20,1224,19,20,Beginner Level,1 hour,2015-07-10 19:53:56+00:00,Musical Instruments
26,486240,2 Easy Steps To Investment And Avoiding Traps,True,20,828,1,20,All Levels,1 hour,2015-04-27 23:18:59+00:00,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3675,551170,Your First Course on Piano,True,70,2002,34,33,Beginner Level,4 hours,2015-07-16 17:07:49+00:00,Musical Instruments
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26 20:48:48+00:00,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20 22:15:17+00:00,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26 20:04:21+00:00,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11 18:55:45+00:00,Web Development